export interface Product {
  id: number;
  type: "trees" | "fertilizers";
  category: string;
  name: string;
  price: number;
  oldPrice: number | null;
  rating: number;
  reviews: number;
  badge: string | null;
  badgeLabel: string | null;
  tags: string[];
  img: string;
  desc: string;
  sameDay: boolean;
  size: string | null;
}

export const PRODUCTS: Product[] = [
  // TREES & PLANTS
  {
    id: 1,
    type: "trees",
    category: "Indoor Plants",
    name: "Fiddle Leaf Fig",
    price: 1299,
    oldPrice: 1599,
    rating: 4.9,
    reviews: 124,
    badge: "sale",
    badgeLabel: "-20%",
    tags: ["Indoor", "Low Light"],
    img: "https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?w=500&q=75",
    desc: "A stunning statement plant with large, waxy leaves. Perfect for bright, indirect light.",
    sameDay: true,
    size: "medium",
  },
  {
    id: 2,
    type: "trees",
    category: "Fruit Tree",
    name: "Dwarf Alphonso Mango",
    price: 2199,
    oldPrice: null,
    rating: 4.6,
    reviews: 67,
    badge: "hot",
    badgeLabel: "Hot",
    tags: ["Fruit", "Outdoor"],
    img: "https://images.unsplash.com/photo-1621380401601-1c0e2e83c19e?w=500&q=75",
    desc: "Bears real Alphonso mangoes in a compact 4–5ft form. Great for balconies and gardens.",
    sameDay: false,
    size: "large",
  },
  {
    id: 3,
    type: "trees",
    category: "Bonsai",
    name: "Ficus Bonsai Starter Kit",
    price: 899,
    oldPrice: 1049,
    rating: 4.4,
    reviews: 41,
    badge: "sale",
    badgeLabel: "-15%",
    tags: ["Bonsai", "Indoor"],
    img: "https://images.unsplash.com/photo-1512428813834-c702c7702b78?w=500&q=75",
    desc: "Includes a pre-shaped ficus bonsai, pot, soil, and a beginner care booklet.",
    sameDay: true,
    size: "small",
  },
  {
    id: 4,
    type: "trees",
    category: "Flowering Shrub",
    name: "Double Hibiscus — Red",
    price: 549,
    oldPrice: null,
    rating: 4.8,
    reviews: 57,
    badge: "new",
    badgeLabel: "New",
    tags: ["Flowering", "Outdoor"],
    img: "https://images.unsplash.com/photo-1592150621744-aca64f48394a?w=500&q=75",
    desc: "Vibrant double-layered blooms all year round. Thrives in full sun with minimal care.",
    sameDay: true,
    size: "small",
  },
  {
    id: 5,
    type: "trees",
    category: "Indoor Plants",
    name: "Monstera Deliciosa",
    price: 799,
    oldPrice: null,
    rating: 4.7,
    reviews: 198,
    badge: "new",
    badgeLabel: "New",
    tags: ["Indoor", "Tropical"],
    img: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=500&q=75",
    desc: "Iconic split-leaf tropical plant. Grows beautifully indoors with bright indirect light.",
    sameDay: true,
    size: "medium",
  },
  {
    id: 6,
    type: "trees",
    category: "Outdoor Trees",
    name: "Indian Coral Tree",
    price: 1899,
    oldPrice: null,
    rating: 4.5,
    reviews: 33,
    badge: null,
    badgeLabel: null,
    tags: ["Ornamental", "Outdoor"],
    img: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=500&q=75",
    desc: "Brilliant red blooms attract birds and butterflies. Grows vigorously in gardens.",
    sameDay: false,
    size: "large",
  },
  {
    id: 7,
    type: "trees",
    category: "Fruit Tree",
    name: "Dwarf Lemon Tree",
    price: 1499,
    oldPrice: 1799,
    rating: 4.7,
    reviews: 82,
    badge: "sale",
    badgeLabel: "-17%",
    tags: ["Fruit", "Balcony"],
    img: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=500&q=75",
    desc: "Compact lemon tree that fruits year-round. Ideal for balconies and sunny patios.",
    sameDay: false,
    size: "medium",
  },
  {
    id: 8,
    type: "trees",
    category: "Indoor Plants",
    name: "Snake Plant — Gold Edge",
    price: 449,
    oldPrice: null,
    rating: 4.9,
    reviews: 312,
    badge: null,
    badgeLabel: null,
    tags: ["Indoor", "Air Purifier"],
    img: "https://images.unsplash.com/photo-1572688484438-313a6e50c333?w=500&q=75",
    desc: "Nearly indestructible air-purifying plant. Perfect for offices and bedrooms.",
    sameDay: true,
    size: "small",
  },
  {
    id: 9,
    type: "trees",
    category: "Bonsai",
    name: "Jade Bonsai (5yr)",
    price: 2499,
    oldPrice: null,
    rating: 4.6,
    reviews: 28,
    badge: null,
    badgeLabel: null,
    tags: ["Bonsai", "Succulent"],
    img: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500&q=75",
    desc: "A beautifully shaped 5-year-old jade bonsai, ready to display.",
    sameDay: false,
    size: "small",
  },
  // FERTILIZERS
  {
    id: 10,
    type: "fertilizers",
    category: "NPK Fertilizer",
    name: "NPK Premium Blend 20-20-20",
    price: 449,
    oldPrice: null,
    rating: 4.9,
    reviews: 89,
    badge: "organic",
    badgeLabel: "Organic",
    tags: ["NPK", "All Plants"],
    img: "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=500&q=75",
    desc: "Balanced all-purpose fertilizer suitable for every plant type. Water-soluble formula.",
    sameDay: true,
    size: null,
  },
  {
    id: 11,
    type: "fertilizers",
    category: "Organic / Compost",
    name: "Premium Vermicompost 5kg",
    price: 299,
    oldPrice: null,
    rating: 5.0,
    reviews: 203,
    badge: "organic",
    badgeLabel: "Organic",
    tags: ["Compost", "Soil"],
    img: "https://images.unsplash.com/photo-1603436326446-74c1e516f6d0?w=500&q=75",
    desc: "100% organic vermicompost. Improves soil structure and microbial activity naturally.",
    sameDay: true,
    size: null,
  },
  {
    id: 12,
    type: "fertilizers",
    category: "Liquid Fertilizer",
    name: "Seaweed Growth Booster",
    price: 349,
    oldPrice: 399,
    rating: 4.7,
    reviews: 54,
    badge: "sale",
    badgeLabel: "-12%",
    tags: ["Liquid", "Growth"],
    img: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=500&q=75",
    desc: "Cold-processed seaweed extract rich in cytokinins and natural growth hormones.",
    sameDay: false,
    size: null,
  },
  {
    id: 13,
    type: "fertilizers",
    category: "NPK Fertilizer",
    name: "Rose & Flower Booster",
    price: 279,
    oldPrice: null,
    rating: 4.6,
    reviews: 71,
    badge: null,
    badgeLabel: null,
    tags: ["Flowering", "NPK"],
    img: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&q=75",
    desc: "High-phosphorus formula for prolific blooming. Great for hibiscus, roses, and jasmine.",
    sameDay: true,
    size: null,
  },
  {
    id: 14,
    type: "fertilizers",
    category: "Organic / Compost",
    name: "Neem Cake Fertilizer 3kg",
    price: 199,
    oldPrice: null,
    rating: 4.8,
    reviews: 145,
    badge: "organic",
    badgeLabel: "Organic",
    tags: ["Neem", "Pest Control"],
    img: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=500&q=75",
    desc: "Dual-action neem cake — enriches soil while naturally repelling pests and nematodes.",
    sameDay: true,
    size: null,
  },
  {
    id: 15,
    type: "fertilizers",
    category: "Liquid Fertilizer",
    name: "Calcium & Magnesium Blend",
    price: 399,
    oldPrice: 499,
    rating: 4.5,
    reviews: 38,
    badge: "sale",
    badgeLabel: "-20%",
    tags: ["Deficiency", "Liquid"],
    img: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=500&q=75",
    desc: "Corrects calcium & magnesium deficiencies. Prevents blossom-end rot and leaf curl.",
    sameDay: false,
    size: null,
  },
  {
    id: 16,
    type: "fertilizers",
    category: "NPK Fertilizer",
    name: "Fruit Tree Special 12-8-16",
    price: 529,
    oldPrice: null,
    rating: 4.7,
    reviews: 62,
    badge: null,
    badgeLabel: null,
    tags: ["Fruit Trees", "NPK"],
    img: "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=500&q=75",
    desc: "High-potassium blend designed specifically for fruit-bearing trees and shrubs.",
    sameDay: false,
    size: null,
  },
];
